- name: Update and upgrade apt packages
  hosts: all
  become: true

  tasks:
  - name: update and upgrade linux packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day