- name: Terminate EC2 instance using Ansible
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Terminate EC2 instance
      amazon.aws.ec2_instance:
        region: us-east-1
        state: absent
        filters:
          tag:Name: ansible_instance
          instance-state-name: running
